name: CI Pipeline for GPA Mate

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
      fail-fast: false 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint
        if: always() 

      - name: Run Tests
        run: npm test -- --runInBand
        env:
          CI: true

      - name: Build Next.js App
        run: npm run build

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Check for Exposed Secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality-gates:
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - name: Quality Gate Check
        run: echo "All tests and security scans passed. Ready for deployment!"
